name: CD

on:
  push:
    tags:
      - 'release-**'

jobs:
  deploy:
    uses: titicacadev/triple-actions/.github/workflows/web-cd.yml@v1
    with:
      aws-region: ap-northeast-1
      aws-assets-path: recommendation-ai
      sentry-project: triple-recommendation-ai-web
      no-prod-suffix: true
    secrets: inherit
